LTO_ENABLE = yes
SPLIT_KEYBOARD = yes

ENCODER_ENABLE = yes
OLED_ENABLE = yes

MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
CAPS_WORD_ENABLE = no
